// Generated by CoffeeScript 1.6.3
(function() {
  window.Todos = Ember.Application.create();

  Todos.ApplicationAdapter = DS.LSAdapter.extend({
    namespace: 'todos-emberjs'
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
