// Generated by CoffeeScript 1.6.3
(function() {
  Todos.EditTodoView = Ember.TextField.extend({
    didInsertElement: function() {
      return this.$().focus();
    }
  });

  Ember.Handlebars.helper('edit-todo', Todos.EditTodoView);

}).call(this);

/*
//@ sourceMappingURL=edit_todo_view.map
*/
