// Generated by CoffeeScript 1.6.3
(function() {
  Todos.TodosController = Ember.ArrayController.extend({
    actions: {
      createTodo: function() {
        var title, todo;
        title = this.get('newTitle');
        if (!title.trim()) {
          return;
        }
        todo = this.store.createRecord('todo', {
          title: title,
          isCompleted: false
        });
        this.set('newTitle', '');
        return todo.save();
      },
      clearCompleted: function() {
        var completed;
        completed = this.filterProperty('isCompleted', true);
        completed.invoke('deleteRecord');
        return completed.invoke('save');
      }
    },
    remaining: (function() {
      return this.filterProperty('isCompleted', false).get('length');
    }).property('@each.isCompleted'),
    inflection: (function() {
      var remaining;
      remaining = this.get('remaining');
      if (remaining === 1) {
        return 'item';
      } else {
        return 'items';
      }
    }).property('remaining'),
    hasCompleted: (function() {
      return this.get('completed') > 0;
    }).property('completed'),
    completed: (function() {
      return this.filterProperty('isCompleted', true).get('length');
    }).property('@each.isCompleted'),
    allAreDone: (function(key, value) {
      if (value === void 0) {
        return !!this.get('length') && this.everyProperty('isCompleted', true);
      } else {
        this.setEach('isCompleted', value);
        this.invoke('save');
        return value;
      }
    }).property('@each.isCompleted')
  });

}).call(this);
