// Generated by CoffeeScript 1.6.3
(function() {
  Todos.TodoController = Ember.ObjectController.extend({
    actions: {
      editTodo: function() {
        return this.set('isEditing', true);
      },
      acceptChanges: function() {
        this.set('isEditing', false);
        return this.get('model').save();
      },
      removeTodo: function() {
        var todo;
        todo = this.get('model');
        todo.deleteRecord();
        return todo.save();
      }
    },
    isEditing: false,
    isCompleted: (function(key, value) {
      var model;
      model = this.get('model');
      if (value === void 0) {
        return model.get('isCompleted');
      } else {
        model.set('isCompleted', value);
        model.save();
        return value;
      }
    }).property('model.isCompleted')
  });

}).call(this);
